# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "ios actions"

  lane :build_ci do
    desc "simple build"
    setup_ci
    match(type: "appstore", readonly: is_ci, force_for_new_devices: true)
    build_app(scheme: "Fruits")
  end

  lane :beta_ci do
    desc "Build and upload to TestFlight"
    setup_ci
    match(type: "appstore", readonly: is_ci, force_for_new_devices: true)
    increment_build_number(xcodeproj: "Fruits.xcodeproj")
    commit_version_bump
    build_app(scheme: "Fruits")
    app_store_connect_api_key
    upload_to_testflight
  end

  lane :beta do
    match(type: "appstore", readonly: is_ci)
    increment_build_number(xcodeproj: "Fruits.xcodeproj")
    build_app(scheme: "Fruits")
  end

  lane :tests do
    desc "Run all tests"
    run_tests
  end

end
